"""Canonical index aliases, board membership, and display configuration."""

FETCH_SYMBOLS: dict[str, str] = {
    "^CNXMIDCAP": "NIFTY_MIDCAP_100.NS",
    "^NIFTYNXT50": "NIFTY_NEXT_50.NS",
    "^NSESMCP100": "NIFTY_SMLCAP_100.NS",
    "^CNXDEFENCE": "NIFTY_IND_DEFENCE.NS",
}

NORMALIZATION_ALIASES: dict[str, str] = {
    "^NSEMDCP100": "^CNXMIDCAP",
    "NIFTYMIDCAP100.NS": "^CNXMIDCAP",
    "NIFTY_MIDCAP_100.NS": "^CNXMIDCAP",
    "^NSESMCP250": "^NSESMCP100",
    "NIFTY_SMALLCAP_100.NS": "^NSESMCP100",
    "NIFTY_SMLCAP_100.NS": "^NSESMCP100",
    "NIFTY_NEXT_50.NS": "^NIFTYNXT50",
    "NIFTY_IND_DEFENCE.NS": "^CNXDEFENCE",
}

INDIA_BOARD = (
    ("^NSEI", "NIFTY 50"),
    ("^NSEBANK", "NIFTY BANK"),
    ("^CNXIT", "NIFTY IT"),
    ("^CNXMIDCAP", "NIFTY MIDCAP 100"),
    ("^NSEMDCP50", "NIFTY MIDCAP SELECT"),
    ("^NIFTYNXT50", "NIFTY NEXT 50"),
    ("^CNXINFRA", "NIFTY INFRA"),
    ("^CNXPSE", "NIFTY PSE"),
    ("^CNXAUTO", "NIFTY AUTO"),
    ("^CNXENERGY", "NIFTY ENERGY"),
    ("^CNXDEFENCE", "NIFTY DEFENCE"),
    ("^CNXFMCG", "NIFTY FMCG"),
    ("^CNXMEDIA", "NIFTY MEDIA"),
    ("^CNXMETAL", "NIFTY METAL"),
    ("^CNXMNC", "NIFTY MNC"),
    ("^CNXPHARMA", "NIFTY PHARMA"),
    ("^CNXPSUBANK", "NIFTY PSU BANK"),
    ("^CNXREALTY", "NIFTY REALTY"),
    ("NIFTY_FIN_SERVICE.NS", "NIFTY FIN SERVICE"),
    ("^CNXCONSUM", "NIFTY CONSUMPTION"),
    ("^INDIAVIX", "INDIA VIX"),
    ("^NSESMCP100", "NIFTY SMALLCAP 100"),
)

GLOBAL_BOARD = (
    ("^FTSE", "FTSE 100"),
    ("^FCHI", "CAC 40"),
    ("^HSI", "HANG SENG"),
    ("^N225", "NIKKEI 225"),
    ("^IXIC", "NASDAQ"),
    ("^DJI", "DOW JONES"),
)

ALIASES: dict[str, str] = {
    "NIFTY": "^NSEI",
    "NIFTY50": "^NSEI",
    "NIFTY 50": "^NSEI",
    "NIFTYBANK": "^NSEBANK",
    "NIFTY BANK": "^NSEBANK",
    "BANKNIFTY": "^NSEBANK",
    "NSEBANK": "^NSEBANK",
    "BANK": "^NSEBANK",
    "MIDCAP": "^CNXMIDCAP",
    "MIDCAP100": "^CNXMIDCAP",
    "NIFTYMIDCAP100": "^CNXMIDCAP",
    "NIFTY MIDCAP 100": "^CNXMIDCAP",
    "MIDCAPSELECT": "^NSEMDCP50",
    "MIDCAP SELECT": "^NSEMDCP50",
    "NIFTYMIDCAPSELECT": "^NSEMDCP50",
    "NIFTY MIDCAP SELECT": "^NSEMDCP50",
    "MID SELECT": "^NSEMDCP50",
    "SELECT": "^NSEMDCP50",
    "SMALLCAP": "^NSESMCP100",
    "SMALLCAP100": "^NSESMCP100",
    "NIFTYSMALLCAP100": "^NSESMCP100",
    "NIFTY SMALLCAP 100": "^NSESMCP100",
    "VIX": "^INDIAVIX",
    "INDIAVIX": "^INDIAVIX",
    "INDIA VIX": "^INDIAVIX",
    "NIFTY IT": "^CNXIT",
    "NIFTYIT": "^CNXIT",
    "IT": "^CNXIT",
    "FINNIFTY": "NIFTY_FIN_SERVICE.NS",
    "NIFTYFIN": "NIFTY_FIN_SERVICE.NS",
    "NIFTY FIN SERVICE": "NIFTY_FIN_SERVICE.NS",
    "NIFTYFINSERVICE": "NIFTY_FIN_SERVICE.NS",
    "NIFTY FINANCE": "NIFTY_FIN_SERVICE.NS",
    "NIFTYFINANCE": "NIFTY_FIN_SERVICE.NS",
    "FIN": "NIFTY_FIN_SERVICE.NS",
    "FINANCE": "NIFTY_FIN_SERVICE.NS",
    "NIFTYFMCG": "^CNXFMCG",
    "NIFTY FMCG": "^CNXFMCG",
    "FMCG": "^CNXFMCG",
    "NIFTYPSE": "^CNXPSE",
    "NIFTY PSE": "^CNXPSE",
    "PSE": "^CNXPSE",
    "CPSE": "^CNXPSE",
    "NIFTYAUTO": "^CNXAUTO",
    "NIFTY AUTO": "^CNXAUTO",
    "AUTO": "^CNXAUTO",
    "NIFTYINFRA": "^CNXINFRA",
    "NIFTY INFRA": "^CNXINFRA",
    "INFRA": "^CNXINFRA",
    "NIFTYENERGY": "^CNXENERGY",
    "NIFTY ENERGY": "^CNXENERGY",
    "ENERGY": "^CNXENERGY",
    "NIFTYMEDIA": "^CNXMEDIA",
    "NIFTY MEDIA": "^CNXMEDIA",
    "MEDIA": "^CNXMEDIA",
    "NIFTYMETAL": "^CNXMETAL",
    "NIFTY METAL": "^CNXMETAL",
    "METAL": "^CNXMETAL",
    "METALS": "^CNXMETAL",
    "NIFTYMNC": "^CNXMNC",
    "NIFTY MNC": "^CNXMNC",
    "MNC": "^CNXMNC",
    "NIFTYREALTY": "^CNXREALTY",
    "NIFTY REALTY": "^CNXREALTY",
    "REALTY": "^CNXREALTY",
    "NIFTYPHARMA": "^CNXPHARMA",
    "NIFTY PHARMA": "^CNXPHARMA",
    "PHARMA": "^CNXPHARMA",
    "NIFTYCONSUMPTION": "^CNXCONSUM",
    "NIFTY CONSUMPTION": "^CNXCONSUM",
    "NIFTYCONSUMER": "^CNXCONSUM",
    "NIFTY CONSUMER": "^CNXCONSUM",
    "CONSUMPTION": "^CNXCONSUM",
    "CONSUMER": "^CNXCONSUM",
    "CONSUMERS": "^CNXCONSUM",
    "NEXT50": "^NIFTYNXT50",
    "NIFTYNEXT50": "^NIFTYNXT50",
    "NIFTY NEXT 50": "^NIFTYNXT50",
    "NIFTYDEFENCE": "^CNXDEFENCE",
    "NIFTY DEFENCE": "^CNXDEFENCE",
    "NIFTYDEFENSE": "^CNXDEFENCE",
    "NIFTY DEFENSE": "^CNXDEFENCE",
    "DEFENCE": "^CNXDEFENCE",
    "DEFENSE": "^CNXDEFENCE",
    "PSUBANK": "^CNXPSUBANK",
    "NIFTYPSUBANK": "^CNXPSUBANK",
    "NIFTY PSU BANK": "^CNXPSUBANK",
    "PSU": "^CNXPSUBANK",
    "SENSEX": "^BSESN",
    "BSE SENSEX": "^BSESN",
    "NASDAQ": "^IXIC",
    "NASADQ": "^IXIC",
    "DOW": "^DJI",
    "DOWJONES": "^DJI",
    "HANGSENG": "^HSI",
    "HANG SENG": "^HSI",
    "NIKKEI": "^N225",
    "NIKKEI225": "^N225",
    "FTSE": "^FTSE",
    "FTSE100": "^FTSE",
    "FTSE 100": "^FTSE",
    "SP": "^GSPC",
    "S&P": "^GSPC",
    "S&P500": "^GSPC",
    "SP500": "^GSPC",
}

EXPECTED_CONSTITUENT_COUNTS: dict[str, int] = {
    "^NSEI": 50,
    "^NIFTYNXT50": 50,
    "^CNXMIDCAP": 100,
    "^NSEMDCP50": 25,
    "^NSESMCP100": 100,
    "^FTSE": 100,
    "^FCHI": 40,
    "^N225": 225,
    "^DJI": 30,
}

SNAP_ALLOWED_SYMBOLS: set[str] = {
    *(symbol for symbol, _label in INDIA_BOARD if symbol != "^INDIAVIX"),
    "^DJI",
}

BOARD_SYMBOLS: set[str] = {
    *(symbol.upper() for symbol, _label in INDIA_BOARD),
    *(symbol.upper() for symbol, _label in GLOBAL_BOARD),
}

PROMPT_LABELS: dict[str, str] = {
    "^NSEI": "nifty",
    "^NSEBANK": "bank",
    "^CNXIT": "it",
    "^CNXMIDCAP": "midcap",
    "^NSEMDCP50": "midcapselect",
    "^NIFTYNXT50": "next50",
    "^CNXINFRA": "infra",
    "^CNXPSE": "pse",
    "^CNXAUTO": "auto",
    "^CNXENERGY": "energy",
    "^CNXDEFENCE": "defence",
    "^CNXFMCG": "fmcg",
    "^CNXMEDIA": "media",
    "^CNXMETAL": "metal",
    "^CNXMNC": "mnc",
    "^CNXPHARMA": "pharma",
    "^CNXPSUBANK": "psubank",
    "^CNXREALTY": "realty",
    "NIFTY_FIN_SERVICE.NS": "fin",
    "^CNXCONSUM": "consumer",
    "^INDIAVIX": "vix",
    "^NSESMCP100": "smallcap",
    "^FTSE": "ftse",
    "^FCHI": "cac",
    "^HSI": "hangseng",
    "^N225": "nikkei",
    "^IXIC": "nasdaq",
    "^DJI": "dow",
}
